### ISSUE TITLE
unable to install apps while service is active

### ISSUE THREAD

**Issue by Aydan** [takke/DataStats#25]
Since version 2.4.1 I'm unable to activate the install button of the app installer with datastats service running.
This is on CM13.0.

**Comment by tbone2k-git** [comment]
Me too! o) I also opened an issue for this problem, I'm on Cyanogen as well (CM11 iirc). In the meantime, I downgraded to v2.3.3 from here (the former releases on F-Droid also don't seem to be available anymore):
https://www.apkmonk.com/download-app/jp.takke.datastats/2_jp.takke.datastats_2015-09-18.apk/

**Comment by sitaramc** [comment]
It also happens when you access other functions like grant device admin (lock screen) rights to some app.  I think it has something to do with the ability to "draw over other apps" which is obscuring those buttons.

But I am not an Android dev, so this is just a wild guess.

(Just to be clear, I have the problem also, on a stock Samsun J2 running 6.0.<whatever>)

**Comment by takke** [comment]
Please  update to version 2.5.0 and use show/hide button on notification bar.
Thanks.
